{{ if and .Values.versions.create (.Capabilities.APIVersions.Has "stack.formance.com/v1beta3/Versions") }}
apiVersion: stack.formance.com/v1beta3
kind: Versions
metadata:
  name: v2.0
spec:
  ledger: v2.0.0-rc.7
  search: v2.0.0-rc.7
  stargate: v2.0.0-rc.7
  auth: v2.0.0-rc.7
  wallets: v2.0.0-rc.7
  webhooks: v2.0.0-rc.7
  gateway: v2.0.0-rc.7
  payments: v2.0.0-rc.7
  orchestration: v2.0.0-rc.7
  reconciliation: v2.0.0-rc.7
{{ end }}
